### ISSUE TITLE
Offset filter for get requests

### ISSUE THREAD

**Issue by JAYKALIA007** [remotive-io/remote-jobs-api#8]
Hi folks!

So, I am creating a JOBS BOARD project using your API (big thanks btw). 
I'd like to **paginate** my homepage and for that the API has the **limit** parameter, however I guess there isn't an option to **set offset** (using which I'd have implemented the next page option). For now, what I'm doing is fetching all the jobs at once and then **slicing the jobs array** from 0-10, 10-20 by setting state(in React). 

I was wondering if you guys could go ahead and create a **filter for offset** as well or if there's already one, then **mention it in the README file**.

**Comment by adriencombourieu** [comment]
Hi @JAYKALIA007 

Thank you for your interest in our API, please share with us your job board project ;)

I just added the "offset" parameter, that you can use just like you do with "limit", for example:
https://remotive.com/api/remote-jobs?limit=5&offset=5

That said, I am not sure this will be satisfactory for what you are doing, because you might not be able to fully control the _order_ of the jobs... but you can try and let me know how it goes. If it works well, I'll document it!

Also, I am under the feeling that you are doing the API calls from your front-end, generating calls each time your page is displayed. That's not a use case we had in mind but again, let's see if you manage to make it work ;)

We had in mind that our API users would make a call to our API just a couple of times a day (because our data is not changing that fast anyway), then store the data in a database, and then use a front-end based on the database.. in such case the limit/offset could be done on your side. But then you need to maintain the data in the database, by removing the jobs that are not listed in our API anymore - which you don't need to do when doing direct calls to our API from your frontend, as I suspect you do.

let me know how it goes!

**Comment by JAYKALIA007** [comment]
Hi @adriencombourieu 

First of all, thanks for adding the offset filter. It works perfectly in my case.

You said that , I might not be able to fully control the order of the jobs. I didn't quite get what you were trying to say here. Because in my case the filter works perfectly. 

I'm doing the API calls through front-end.
In my homepage, I have a couple of buttons **next** and **prev**. By default the offset is set at 0, every time a user clicks on next, offset gets updated by 10 and vice versa for the prev button. Accordingly, the jobs[] gets updated and the screen gets re-rendered.

I haven't hosted it but you can see the repo(it has screenshots too). 

[JOBS BOARD repo](https://github.com/JAYKALIA007/jobs-board)
